app/models/__init__.py
from .user import User

app/models/posts.py
from app.extensions import db
from datetime import datetime


class Posts(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    # 回复的博客id，默认为0，表示是发的博客
    rid = db.Column(db.Integer, index=True, default=0)
    # 博客内容
    content = db.Column(db.Text)
    # 发表时间
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    # 关联的外键字段(表名.字段)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/models/user.py
from flask import current_app
from app.extensions import db, login_manger
# 导入密码散列及校验函数
from werkzeug.security import generate_password_hash, check_password_hash
# 导入生成和校验token类库
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
# 导入Mixin类库
from flask_login import UserMixin


class User(UserMixin, db.Model):
    # 指定表名
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    email = db.Column(db.String(64), unique=True)
    # 在关联的另一模型中添加一个反向引用
    # 第一个参数：指定关联的另一模型名
    # backref：反向引用的字段名
    # lazy：指定加载方式，dynamic是不加载，但是提供记录查询
    # posts = db.relationship('Posts', backref='user', lazy='dynamic')

    # 生成账户激活时用的token
    def generate_activate_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        # 会将字典信息加密，变成一个加密后的字符串
        return s.dumps({'confirm_id': self.id})

    # 校验用户激活的token
    @staticmethod
    def check_activate_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            # 从用户提交过来的token中获取数据
            data = s.loads(token)
        except:
            return False
        # 根据主键查询数据，判断是否存在该用户
        user = User.query.get(data.get('confirm_id'))
        if user is None:
            # 用户不存在
            return False
        if not user.confirmed:
            # 如果没有激活
            user.confirmed = True
            db.session.add(user)
        return True


    # 保护密码属性，读取时抛出异常
    @property
    def password(self):
        raise AttributeError('密码是不可读属性')

    # 设置密码
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 密码校验
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


@login_manger.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/forms/__init__.py
from .user import RegisterForm, LoginForm, PasswordForm

app/forms/user.py
# 导入表单基础类库
from flask_wtf import FlaskForm
# 导入表单字段类型
from wtforms import StringField, PasswordField, BooleanField, SubmitField
# 导入字段验证器
from wtforms.validators import DataRequired, Email, EqualTo, Length
# 导入字段有效性异常类
from wtforms import ValidationError
# 导入User的模型类
from app.models import User


# 用户注册表单
class RegisterForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(6,30, message='用户名必须在6~30个字符之间')])
    password = PasswordField('密码', validators=[DataRequired(), Length(6,20, message='密码长度不在6~20之间')])
    confirm = PasswordField('确认密码', validators=[EqualTo('password', message='两次密码不一致')])
    email = StringField('邮箱', validators=[Email(message='邮箱格式不正确')])
    submit = SubmitField('立即注册')

    # 自定义表单验证：validate_字段名
    @staticmethod
    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            return ValidationError('该用户已存在，请选用其它名称')

    @staticmethod
    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            return ValidationError('该邮箱已使用，请更换其它邮箱')


# 登录表单
class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    password = PasswordField('密码', validators=[DataRequired()])
    remember_me = BooleanField('记住我')
    submit = SubmitField('立即登录')


# 修改密码表单
class PasswordForm(FlaskForm):
    old_pwd = PasswordField('原密码', validators=[DataRequired()])
    new_pwd = PasswordField('新密码', validators=[DataRequired(), Length(6, 20, message='密码长度不在6~20之间')])
    confirm = PasswordField('确认密码', validators=[EqualTo('new_pwd', message='两次密码不一致')])
    submit = SubmitField('确认修改')

app/__init__.py
from flask import Flask, render_template
from app.config import config
from app.extensions import db, bootstrap, mail, moment, login_manger
from app.views import DEFAULT_BLUEPRINT


def create_app(config_name):
    # 创建Flask实例
    app = Flask(__name__)
    # 通过对象初始化配置
    app.config.from_object(config[config_name])
    # 调用初始化函数
    config[config_name].init_app(app)
    # 配置相关扩展
    config_extensions(app)
    # 配置各种蓝本
    config_blueprint(app)
    # 配置错误显示
    config_errorhandler(app)
    # 返回Flask实例
    return app


def config_extensions(app):
    db.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    login_manger.init_app(app)
    # 默认'basic'，另外None禁用，'strong'用户信息改的立即退出登录
    login_manger.session_protection = 'strong'
    # 设置登录页面的端点(视图函数)，访问选用登录才有权限的URL时自动跳转
    login_manger.login_view = 'user.login'
    # 需要登录时的提示信息，默认是英文字符串
    login_manger.login_message = '需要登录才可访问'


def config_blueprint(app):
    for blue_print, url_prefix in DEFAULT_BLUEPRINT:
        app.register_blueprint(blue_print, url_prefix=url_prefix)


def config_errorhandler(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('errors/404.html')

app/views/__init__.py
from .main import main
from .user import user
from .posts import posts


# 默认蓝本配置
DEFAULT_BLUEPRINT = (
    # (蓝本名称，URL前缀)
    (main, ''),
    (user, '/user'),
    (posts, '/posts')
)

app/views/main.py
from flask import Blueprint, render_template


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')

app/views/posts.py
from flask import Blueprint

posts = Blueprint('posts', __name__)


@posts.route('/send/')
def send():
    return '发表博客'

app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from app.forms import RegisterForm, LoginForm, PasswordForm
from app.email import send_mail
from app.models import User
from app.extensions import db
from flask_login import login_user, logout_user, login_required, current_user


user = Blueprint('user', __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 创建新用户
        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        # 添加到数据库
        db.session.add(u)
        # 此处需要手动提交，因为请求结束后才会执行SQL，才会生成 id
        # 而产出token时需要用到id
        db.session.commit()
        # 发送激活邮件
        token = u.generate_activate_token()
        send_mail(form.email.data, '账户激活', 'email/account_activate', token=token, user=u)
        # 给出flash消息
        flash('邮件已经发送至您的邮箱，请点击链接完成激活')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


@user.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        flash('您的账户已激活，可以直接登录')
        return redirect(url_for('user.login'))
    else:
        flash('无效的链接')
        return redirect(url_for('main.index'))


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if u is None:
            flash('无效的用户名')
        elif u.verify_password(form.password.data):
            # 用户登录，顺便完成了 '记住我' 的功能
            login_user(u, remember=form.remember_me.data)
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('无效的密码')
    return render_template('user/login.html', form=form)


@user.route('/logout/')
# 路由保护，需要登录才可访问
@login_required
def logout():
    logout_user()
    flash('您已退出登录')
    return redirect(url_for('main.index'))


@user.route('/profile/')
@login_required
def profile():
    return render_template('user/profile.html')


@user.route('/change_password/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_pwd.data):
            current_user.password = form.new_pwd.data
            db.session.add(current_user)
            flash('密码修改成功，下次登录请使用新密码')
            return redirect(url_for('main.index'))
        else:
            flash('无效的原始密码')
            return redirect(url_for('user.change_password'))
    return render_template('user/change_password.html', form=form)

app/templates/common/base.html
{# 继承自bootstrap的基础模板 #}
{% extends 'bootstrap/base.html' %}

{# 导入wtf #}
{% import 'bootstrap/wtf.html' as wtf %}

{% block navbar %}
<nav class="navbar navbar-inverse" style="border-radius: 0px;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target=".navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{url_for('main.index')}}">首页</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">板块一</a></li>
                <li><a href="#">板块二</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('user.logout')}}">退出</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{current_user.username}}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('user.profile')}}">用户信息</a></li>
                        <li><a href="{{url_for('user.change_password')}}">修改密码</a></li>
                        <li><a href="#">更换邮箱</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{url_for('user.login')}}">登录</a></li>
                <li><a href="{{url_for('user.register')}}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">
            &times;
        </button>
        {{message}}
    </div>
    {% endfor %}
    {% block page_content %}默认内容{% endblock %}
</div>
{% endblock %}

{# 加载网站图标 #}
{% block head %}
{{ super() }}
<link type="image/x-icon" rel="icon" href="{{url_for('static', filename='favicon.ico')}}" />
{% endblock %}

app/templates/main/index.html
{% extends 'common/base.html' %}

{% block title %}首页{% endblock %}

{% block page_content %}
    欢迎访问本博客
{% endblock %}

app/templates/user/change_password.html
{% extends 'common/base.html' %}

{% block title %}修改密码{% endblock %}

{% block page_content %}
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/login.html
{% extends 'common/base.html' %}

{% block title %}欢迎登录{% endblock %}

{% block page_content %}
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/user/profile.html
{% extends 'common/base.html' %}

{% block title %}个人中心{% endblock %}

{% block page_content %}
<div class="form-group">
    <label for="userinput">用户名</label>
    <input type="text" class="form-control" id="userinput" readonly value="{{current_user.username}}">
</div>
<div class="form-group">
    <label for="emailinput">邮箱</label>
    <input type="email" class="form-control" id="emailinput" readonly value="{{current_user.email}}">
</div>
{% endblock %}

app/templates/user/register.html
{% extends 'common/base.html' %}

{% block title %}欢迎注册{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}